apiVersion: v1
data:
  root-pass: Um9vdFBhc3MxMjM=
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: php-three-tier
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2026-09-08T14:18:16Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: mysql-secret
  namespace: default
  resourceVersion: "142777"
  uid: 61d8cfcb-a506-4485-9974-8395bf61d38d
type: Opaque
